<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Kota;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kota = [
            ['kota' => 'KABUPATEN SIMEULUE', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH SINGKIL', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH SELATAN', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH TENGGARA', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH TIMUR', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH TENGAH', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH BARAT', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH BESAR', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN PIDIE', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN BIREUEN', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH UTARA', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH BARAT DAYA', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN GAYO LUES', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH TAMIANG', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN NAGAN RAYA', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN ACEH JAYA', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN BENER MERIAH', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN PIDIE JAYA', 'id_provinsi' => 11],
            ['kota' => 'KOTA BANDA ACEH', 'id_provinsi' => 11],
            ['kota' => 'KOTA SABANG', 'id_provinsi' => 11],
            ['kota' => 'KOTA LANGSA', 'id_provinsi' => 11],
            ['kota' => 'KOTA LHOKSEUMAWE', 'id_provinsi' => 11],
            ['kota' => 'KOTA SUBULUSSALAM', 'id_provinsi' => 11],
            ['kota' => 'KABUPATEN NIAS', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN MANDAILING NATAL', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN TAPANULI SELATAN', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN TAPANULI TENGAH', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN TAPANULI UTARA', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN TOBA SAMOSIR', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN LABUHAN BATU', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN ASAHAN', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN SIMALUNGUN', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN DAIRI', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN KARO', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN DELI SERDANG', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN LANGKAT', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN NIAS SELATAN', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN HUMBANG HASUNDUTAN', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN PAKPAK BHARAT', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN SAMOSIR', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN SERDANG BEDAGAI', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN BATU BARA', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN PADANG LAWAS UTARA', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN PADANG LAWAS', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN LABUHAN BATU SELATAN', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN LABUHAN BATU UTARA', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN NIAS UTARA', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN NIAS BARAT', 'id_provinsi' => 12],
            ['kota' => 'KOTA SIBOLGA', 'id_provinsi' => 12],
            ['kota' => 'KOTA TANJUNG BALAI', 'id_provinsi' => 12],
            ['kota' => 'KOTA PEMATANG SIANTAR', 'id_provinsi' => 12],
            ['kota' => 'KOTA TEBING TINGGI', 'id_provinsi' => 12],
            ['kota' => 'KOTA MEDAN', 'id_provinsi' => 12],
            ['kota' => 'KOTA BINJAI', 'id_provinsi' => 12],
            ['kota' => 'KOTA PADANGSIDIMPUAN', 'id_provinsi' => 12],
            ['kota' => 'KOTA GUNUNGSITOLI', 'id_provinsi' => 12],
            ['kota' => 'KABUPATEN KEPULAUAN MENTAWAI', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN PESISIR SELATAN', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN SOLOK', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN SIJUNJUNG', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN TANAH DATAR', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN PADANG PARIAMAN', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN AGAM', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN LIMA PULUH KOTA', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN PASAMAN', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN SOLOK SELATAN', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN DHARMASRAYA', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN PASAMAN BARAT', 'id_provinsi' => 13],
            ['kota' => 'KOTA PADANG', 'id_provinsi' => 13],
            ['kota' => 'KOTA SOLOK', 'id_provinsi' => 13],
            ['kota' => 'KOTA SAWAH LUNTO', 'id_provinsi' => 13],
            ['kota' => 'KOTA PADANG PANJANG', 'id_provinsi' => 13],
            ['kota' => 'KOTA BUKITTINGGI', 'id_provinsi' => 13],
            ['kota' => 'KOTA PAYAKUMBUH', 'id_provinsi' => 13],
            ['kota' => 'KOTA PARIAMAN', 'id_provinsi' => 13],
            ['kota' => 'KABUPATEN KUANTAN SINGINGI', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN INDRAGIRI HULU', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN INDRAGIRI HILIR', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN PELALAWAN', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN S I A K', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN KAMPAR', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN ROKAN HULU', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN BENGKALIS', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN ROKAN HILIR', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN KEPULAUAN MERANTI', 'id_provinsi' => 14],
            ['kota' => 'KOTA PEKANBARU', 'id_provinsi' => 14],
            ['kota' => 'KOTA D U M A I', 'id_provinsi' => 14],
            ['kota' => 'KABUPATEN KERINCI', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN MERANGIN', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN SAROLANGUN', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN BATANG HARI', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN MUARO JAMBI', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN TANJUNG JABUNG BARAT', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN TEBO', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN BUNGO', 'id_provinsi' => 15],
            ['kota' => 'KOTA JAMBI', 'id_provinsi' => 15],
            ['kota' => 'KOTA SUNGAI PENUH', 'id_provinsi' => 15],
            ['kota' => 'KABUPATEN OGAN KOMERING ULU', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN OGAN KOMERING ILIR', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN MUARA ENIM', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN LAHAT', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN MUSI RAWAS', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN MUSI BANYUASIN', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN BANYU ASIN', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN OGAN ILIR', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN EMPAT LAWANG', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN MUSI RAWAS UTARA', 'id_provinsi' => 16],
            ['kota' => 'KOTA PALEMBANG', 'id_provinsi' => 16],
            ['kota' => 'KOTA PRABUMULIH', 'id_provinsi' => 16],
            ['kota' => 'KOTA PAGAR ALAM', 'id_provinsi' => 16],
            ['kota' => 'KOTA LUBUKLINGGAU', 'id_provinsi' => 16],
            ['kota' => 'KABUPATEN BENGKULU SELATAN', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN REJANG LEBONG', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN BENGKULU UTARA', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN KAUR', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN SELUMA', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN MUKOMUKO', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN LEBONG', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN KEPAHIANG', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN BENGKULU TENGAH', 'id_provinsi' => 17],
            ['kota' => 'KOTA BENGKULU', 'id_provinsi' => 17],
            ['kota' => 'KABUPATEN LAMPUNG BARAT', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN TANGGAMUS', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN LAMPUNG SELATAN', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN LAMPUNG TIMUR', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN LAMPUNG TENGAH', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN LAMPUNG UTARA', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN WAY KANAN', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN TULANGBAWANG', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN PESAWARAN', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN PRINGSEWU', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN MESUJI', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN TULANG BAWANG BARAT', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN PESISIR BARAT', 'id_provinsi' => 18],
            ['kota' => 'KOTA BANDAR LAMPUNG', 'id_provinsi' => 18],
            ['kota' => 'KOTA METRO', 'id_provinsi' => 18],
            ['kota' => 'KABUPATEN BANGKA', 'id_provinsi' => 19],
            ['kota' => 'KABUPATEN BELITUNG', 'id_provinsi' => 19],
            ['kota' => 'KABUPATEN BANGKA BARAT', 'id_provinsi' => 19],
            ['kota' => 'KABUPATEN BANGKA TENGAH', 'id_provinsi' => 19],
            ['kota' => 'KABUPATEN BANGKA SELATAN', 'id_provinsi' => 19],
            ['kota' => 'KABUPATEN BELITUNG TIMUR', 'id_provinsi' => 19],
            ['kota' => 'KOTA PANGKAL PINANG', 'id_provinsi' => 19],
            ['kota' => 'KABUPATEN KARIMUN', 'id_provinsi' => 21],
            ['kota' => 'KABUPATEN BINTAN', 'id_provinsi' => 21],
            ['kota' => 'KABUPATEN NATUNA', 'id_provinsi' => 21],
            ['kota' => 'KABUPATEN LINGGA', 'id_provinsi' => 21],
            ['kota' => 'KABUPATEN KEPULAUAN ANAMBAS', 'id_provinsi' => 21],
            ['kota' => 'KOTA BATAM', 'id_provinsi' => 21],
            ['kota' => 'KOTA TANJUNG PINANG', 'id_provinsi' => 21],
            ['kota' => 'KABUPATEN KEPULAUAN SERIBU', 'id_provinsi' => 31],
            ['kota' => 'KOTA JAKARTA SELATAN', 'id_provinsi' => 31],
            ['kota' => 'KOTA JAKARTA TIMUR', 'id_provinsi' => 31],
            ['kota' => 'KOTA JAKARTA PUSAT', 'id_provinsi' => 31],
            ['kota' => 'KOTA JAKARTA BARAT', 'id_provinsi' => 31],
            ['kota' => 'KOTA JAKARTA UTARA', 'id_provinsi' => 31],
            ['kota' => 'KABUPATEN BOGOR', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN SUKABUMI', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN CIANJUR', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN BANDUNG', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN GARUT', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN TASIKMALAYA', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN CIAMIS', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN KUNINGAN', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN CIREBON', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN MAJALENGKA', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN SUMEDANG', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN INDRAMAYU', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN SUBANG', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN PURWAKARTA', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN KARAWANG', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN BEKASI', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN BANDUNG BARAT', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN PANGANDARAN', 'id_provinsi' => 32],
            ['kota' => 'KOTA BOGOR', 'id_provinsi' => 32],
            ['kota' => 'KOTA SUKABUMI', 'id_provinsi' => 32],
            ['kota' => 'KOTA BANDUNG', 'id_provinsi' => 32],
            ['kota' => 'KOTA CIREBON', 'id_provinsi' => 32],
            ['kota' => 'KOTA BEKASI', 'id_provinsi' => 32],
            ['kota' => 'KOTA DEPOK', 'id_provinsi' => 32],
            ['kota' => 'KOTA CIMAHI', 'id_provinsi' => 32],
            ['kota' => 'KOTA TASIKMALAYA', 'id_provinsi' => 32],
            ['kota' => 'KOTA BANJAR', 'id_provinsi' => 32],
            ['kota' => 'KABUPATEN CILACAP', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN BANYUMAS', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN PURBALINGGA', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN BANJARNEGARA', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN KEBUMEN', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN PURWOREJO', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN WONOSOBO', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN MAGELANG', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN BOYOLALI', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN KLATEN', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN SUKOHARJO', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN WONOGIRI', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN KARANGANYAR', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN SRAGEN', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN GROBOGAN', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN BLORA', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN REMBANG', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN PATI', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN KUDUS', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN JEPARA', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN DEMAK', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN SEMARANG', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN TEMANGGUNG', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN KENDAL', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN BATANG', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN PEKALONGAN', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN PEMALANG', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN TEGAL', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN BREBES', 'id_provinsi' => 33],
            ['kota' => 'KOTA MAGELANG', 'id_provinsi' => 33],
            ['kota' => 'KOTA SURAKARTA', 'id_provinsi' => 33],
            ['kota' => 'KOTA SALATIGA', 'id_provinsi' => 33],
            ['kota' => 'KOTA SEMARANG', 'id_provinsi' => 33],
            ['kota' => 'KOTA PEKALONGAN', 'id_provinsi' => 33],
            ['kota' => 'KOTA TEGAL', 'id_provinsi' => 33],
            ['kota' => 'KABUPATEN KULON PROGO', 'id_provinsi' => 34],
            ['kota' => 'KABUPATEN BANTUL', 'id_provinsi' => 34],
            ['kota' => 'KABUPATEN GUNUNG KIDUL', 'id_provinsi' => 34],
            ['kota' => 'KABUPATEN SLEMAN', 'id_provinsi' => 34],
            ['kota' => 'KOTA YOGYAKARTA', 'id_provinsi' => 34],
            ['kota' => 'KABUPATEN PACITAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN PONOROGO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN TRENGGALEK', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN TULUNGAGUNG', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN BLITAR', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN KEDIRI', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN MALANG', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN LUMAJANG', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN JEMBER', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN BANYUWANGI', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN BONDOWOSO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN SITUBONDO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN PROBOLINGGO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN PASURUAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN SIDOARJO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN MOJOKERTO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN JOMBANG', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN NGANJUK', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN MADIUN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN MAGETAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN NGAWI', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN BOJONEGORO', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN TUBAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN LAMONGAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN GRESIK', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN BANGKALAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN SAMPANG', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN PAMEKASAN', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN SUMENEP', 'id_provinsi' => 35],
            ['kota' => 'KOTA KEDIRI', 'id_provinsi' => 35],
            ['kota' => 'KOTA BLITAR', 'id_provinsi' => 35],
            ['kota' => 'KOTA MALANG', 'id_provinsi' => 35],
            ['kota' => 'KOTA PROBOLINGGO', 'id_provinsi' => 35],
            ['kota' => 'KOTA PASURUAN', 'id_provinsi' => 35],
            ['kota' => 'KOTA MOJOKERTO', 'id_provinsi' => 35],
            ['kota' => 'KOTA MADIUN', 'id_provinsi' => 35],
            ['kota' => 'KOTA SURABAYA', 'id_provinsi' => 35],
            ['kota' => 'KOTA BATU', 'id_provinsi' => 35],
            ['kota' => 'KABUPATEN PANDEGLANG', 'id_provinsi' => 36],
            ['kota' => 'KABUPATEN LEBAK', 'id_provinsi' => 36],
            ['kota' => 'KABUPATEN TANGERANG', 'id_provinsi' => 36],
            ['kota' => 'KABUPATEN SERANG', 'id_provinsi' => 36],
            ['kota' => 'KOTA TANGERANG', 'id_provinsi' => 36],
            ['kota' => 'KOTA CILEGON', 'id_provinsi' => 36],
            ['kota' => 'KOTA SERANG', 'id_provinsi' => 36],
            ['kota' => 'KOTA TANGERANG SELATAN', 'id_provinsi' => 36],
            ['kota' => 'KABUPATEN JEMBRANA', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN TABANAN', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN BADUNG', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN GIANYAR', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN KLUNGKUNG', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN BANGLI', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN KARANG ASEM', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN BULELENG', 'id_provinsi' => 51],
            ['kota' => 'KOTA DENPASAR', 'id_provinsi' => 51],
            ['kota' => 'KABUPATEN LOMBOK BARAT', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN LOMBOK TENGAH', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN LOMBOK TIMUR', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN SUMBAWA', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN DOMPU', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN BIMA', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN SUMBAWA BARAT', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN LOMBOK UTARA', 'id_provinsi' => 52],
            ['kota' => 'KOTA MATARAM', 'id_provinsi' => 52],
            ['kota' => 'KOTA BIMA', 'id_provinsi' => 52],
            ['kota' => 'KABUPATEN SUMBA BARAT', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN SUMBA TIMUR', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN KUPANG', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN TIMOR TENGAH SELATAN', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN TIMOR TENGAH UTARA', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN BELU', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN ALOR', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN LEMBATA', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN FLORES TIMUR', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN SIKKA', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN ENDE', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN NGADA', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN MANGGARAI', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN ROTE NDAO', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN MANGGARAI BARAT', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN SUMBA TENGAH', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN SUMBA BARAT DAYA', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN NAGEKEO', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN MANGGARAI TIMUR', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN SABU RAIJUA', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN MALAKA', 'id_provinsi' => 53],
            ['kota' => 'KOTA KUPANG', 'id_provinsi' => 53],
            ['kota' => 'KABUPATEN SAMBAS', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN BENGKAYANG', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN LANDAK', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN MEMPAWAH', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN SANGGAU', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN KETAPANG', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN SINTANG', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN KAPUAS HULU', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN SEKADAU', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN MELAWI', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN KAYONG UTARA', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN KUBU RAYA', 'id_provinsi' => 61],
            ['kota' => 'KOTA PONTIANAK', 'id_provinsi' => 61],
            ['kota' => 'KOTA SINGKAWANG', 'id_provinsi' => 61],
            ['kota' => 'KABUPATEN KOTAWARINGIN BARAT', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN KOTAWARINGIN TIMUR', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN KAPUAS', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN BARITO SELATAN', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN BARITO UTARA', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN SUKAMARA', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN LAMANDAU', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN SERUYAN', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN KATINGAN', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN PULANG PISAU', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN GUNUNG MAS', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN BARITO TIMUR', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN MURUNG RAYA', 'id_provinsi' => 62],
            ['kota' => 'KOTA PALANGKA RAYA', 'id_provinsi' => 62],
            ['kota' => 'KABUPATEN TANAH LAUT', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN KOTA BARU', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN BANJAR', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN BARITO KUALA', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN TAPIN', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN HULU SUNGAI SELATAN', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN HULU SUNGAI TENGAH', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN HULU SUNGAI UTARA', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN TABALONG', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN TANAH BUMBU', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN BALANGAN', 'id_provinsi' => 63],
            ['kota' => 'KOTA BANJARMASIN', 'id_provinsi' => 63],
            ['kota' => 'KOTA BANJAR BARU', 'id_provinsi' => 63],
            ['kota' => 'KABUPATEN PASER', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN KUTAI BARAT', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN KUTAI KARTANEGARA', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN KUTAI TIMUR', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN BERAU', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN PENAJAM PASER UTARA', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN MAHAKAM HULU', 'id_provinsi' => 64],
            ['kota' => 'KOTA BALIKPAPAN', 'id_provinsi' => 64],
            ['kota' => 'KOTA SAMARINDA', 'id_provinsi' => 64],
            ['kota' => 'KOTA BONTANG', 'id_provinsi' => 64],
            ['kota' => 'KABUPATEN MALINAU', 'id_provinsi' => 65],
            ['kota' => 'KABUPATEN BULUNGAN', 'id_provinsi' => 65],
            ['kota' => 'KABUPATEN TANA TIDUNG', 'id_provinsi' => 65],
            ['kota' => 'KABUPATEN NUNUKAN', 'id_provinsi' => 65],
            ['kota' => 'KOTA TARAKAN', 'id_provinsi' => 65],
            ['kota' => 'KABUPATEN BOLAANG MONGONDOW', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN MINAHASA', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN KEPULAUAN SANGIHE', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN KEPULAUAN TALAUD', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN MINAHASA SELATAN', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN MINAHASA UTARA', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN SIAU TAGULANDANG BIARO', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN MINAHASA TENGGARA', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'id_provinsi' => 71],
            ['kota' => 'KOTA MANADO', 'id_provinsi' => 71],
            ['kota' => 'KOTA BITUNG', 'id_provinsi' => 71],
            ['kota' => 'KOTA TOMOHON', 'id_provinsi' => 71],
            ['kota' => 'KOTA KOTAMOBAGU', 'id_provinsi' => 71],
            ['kota' => 'KABUPATEN BANGGAI KEPULAUAN', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN BANGGAI', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN MOROWALI', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN POSO', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN DONGGALA', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN TOLI-TOLI', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN BUOL', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN PARIGI MOUTONG', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN TOJO UNA-UNA', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN SIGI', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN BANGGAI LAUT', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN MOROWALI UTARA', 'id_provinsi' => 72],
            ['kota' => 'KOTA PALU', 'id_provinsi' => 72],
            ['kota' => 'KABUPATEN KEPULAUAN SELAYAR', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN BULUKUMBA', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN BANTAENG', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN JENEPONTO', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN TAKALAR', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN GOWA', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN SINJAI', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN MAROS', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN BARRU', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN BONE', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN SOPPENG', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN WAJO', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN SIDENRENG RAPPANG', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN PINRANG', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN ENREKANG', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN LUWU', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN TANA TORAJA', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN LUWU UTARA', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN LUWU TIMUR', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN TORAJA UTARA', 'id_provinsi' => 73],
            ['kota' => 'KOTA MAKASSAR', 'id_provinsi' => 73],
            ['kota' => 'KOTA PAREPARE', 'id_provinsi' => 73],
            ['kota' => 'KOTA PALOPO', 'id_provinsi' => 73],
            ['kota' => 'KABUPATEN BUTON', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN MUNA', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KONAWE', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KOLAKA', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KONAWE SELATAN', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN BOMBANA', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN WAKATOBI', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KOLAKA UTARA', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN BUTON UTARA', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KONAWE UTARA', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KOLAKA TIMUR', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN KONAWE KEPULAUAN', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN MUNA BARAT', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN BUTON TENGAH', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN BUTON SELATAN', 'id_provinsi' => 74],
            ['kota' => 'KOTA KENDARI', 'id_provinsi' => 74],
            ['kota' => 'KOTA BAUBAU', 'id_provinsi' => 74],
            ['kota' => 'KABUPATEN BOALEMO', 'id_provinsi' => 75],
            ['kota' => 'KABUPATEN GORONTALO', 'id_provinsi' => 75],
            ['kota' => 'KABUPATEN POHUWATO', 'id_provinsi' => 75],
            ['kota' => 'KABUPATEN BONE BOLANGO', 'id_provinsi' => 75],
            ['kota' => 'KABUPATEN GORONTALO UTARA', 'id_provinsi' => 75],
            ['kota' => 'KOTA GORONTALO', 'id_provinsi' => 75],
            ['kota' => 'KABUPATEN MAJENE', 'id_provinsi' => 76],
            ['kota' => 'KABUPATEN POLEWALI MANDAR', 'id_provinsi' => 76],
            ['kota' => 'KABUPATEN MAMASA', 'id_provinsi' => 76],
            ['kota' => 'KABUPATEN MAMUJU', 'id_provinsi' => 76],
            ['kota' => 'KABUPATEN MAMUJU UTARA', 'id_provinsi' => 76],
            ['kota' => 'KABUPATEN MAMUJU TENGAH', 'id_provinsi' => 76],
            ['kota' => 'KABUPATEN MALUKU TENGGARA BARAT', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN MALUKU TENGGARA', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN MALUKU TENGAH', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN BURU', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN KEPULAUAN ARU', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN SERAM BAGIAN BARAT', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN SERAM BAGIAN TIMUR', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN MALUKU BARAT DAYA', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN BURU SELATAN', 'id_provinsi' => 81],
            ['kota' => 'KOTA AMBON', 'id_provinsi' => 81],
            ['kota' => 'KOTA TUAL', 'id_provinsi' => 81],
            ['kota' => 'KABUPATEN HALMAHERA BARAT', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN HALMAHERA TENGAH', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN KEPULAUAN SULA', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN HALMAHERA SELATAN', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN HALMAHERA UTARA', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN HALMAHERA TIMUR', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN PULAU MOROTAI', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN PULAU TALIABU', 'id_provinsi' => 82],
            ['kota' => 'KOTA TERNATE', 'id_provinsi' => 82],
            ['kota' => 'KOTA TIDORE KEPULAUAN', 'id_provinsi' => 82],
            ['kota' => 'KABUPATEN FAKFAK', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN KAIMANA', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN TELUK WONDAMA', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN TELUK BINTUNI', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN MANOKWARI', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN SORONG SELATAN', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN SORONG', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN RAJA AMPAT', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN TAMBRAUW', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN MAYBRAT', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN MANOKWARI SELATAN', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN PEGUNUNGAN ARFAK', 'id_provinsi' => 91],
            ['kota' => 'KOTA SORONG', 'id_provinsi' => 91],
            ['kota' => 'KABUPATEN MERAUKE', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN JAYAWIJAYA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN JAYAPURA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN NABIRE', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN KEPULAUAN YAPEN', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN BIAK NUMFOR', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN PANIAI', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN PUNCAK JAYA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN MIMIKA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN BOVEN DIGOEL', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN MAPPI', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN ASMAT', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN YAHUKIMO', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN PEGUNUNGAN BINTANG', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN TOLIKARA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN SARMI', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN KEEROM', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN WAROPEN', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN SUPIORI', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN MAMBERAMO RAYA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN NDUGA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN LANNY JAYA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN MAMBERAMO TENGAH', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN YALIMO', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN PUNCAK', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN DOGIYAI', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN INTAN JAYA', 'id_provinsi' => 94],
            ['kota' => 'KABUPATEN DEIYAI', 'id_provinsi' => 94],
            ['kota' => 'KOTA JAYAPURA', 'id_provinsi' => 94],
        ];

        foreach ($kota as $data) {
            Kota::create($data);
        }
    }
}
