<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Universitas;

class UniversitasSeeder extends Seeder
{
    public function run(): void
    {
       $universitas = [
    ['nama' => 'Universitas Indonesia', 'prodi_id' => 1, 'kode_prodi' => 'UI-01', 'minimal_nilai_utbk' => 740, 'minimal_nilai_snbp' => 930, 'kota' => 'Depok', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Indonesia', 'prodi_id' => 2, 'kode_prodi' => 'UI-02', 'minimal_nilai_utbk' => 710, 'minimal_nilai_snbp' => 900, 'kota' => 'Depok', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Gadjah Mada', 'prodi_id' => 3, 'kode_prodi' => 'UGM-03', 'minimal_nilai_utbk' => 720, 'minimal_nilai_snbp' => 910, 'kota' => 'Sleman', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Gadjah Mada', 'prodi_id' => 4, 'kode_prodi' => 'UGM-04', 'minimal_nilai_utbk' => 705, 'minimal_nilai_snbp' => 880, 'kota' => 'Sleman', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Institut Teknologi Bandung', 'prodi_id' => 5, 'kode_prodi' => 'ITB-05', 'minimal_nilai_utbk' => 730, 'minimal_nilai_snbp' => null, 'kota' => 'Bandung', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Institut Teknologi Bandung', 'prodi_id' => 6, 'kode_prodi' => 'ITB-06', 'minimal_nilai_utbk' => 725, 'minimal_nilai_snbp' => null, 'kota' => 'Bandung', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Airlangga', 'prodi_id' => 7, 'kode_prodi' => 'UNAIR-07', 'minimal_nilai_utbk' => 710, 'minimal_nilai_snbp' => 890, 'kota' => 'Surabaya', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Airlangga', 'prodi_id' => 8, 'kode_prodi' => 'UNAIR-08', 'minimal_nilai_utbk' => 675, 'minimal_nilai_snbp' => 860, 'kota' => 'Surabaya', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Diponegoro', 'prodi_id' => 9, 'kode_prodi' => 'UNDIP-09', 'minimal_nilai_utbk' => 700, 'minimal_nilai_snbp' => 870, 'kota' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
    ['nama' => 'Universitas Diponegoro', 'prodi_id' => 10, 'kode_prodi' => 'UNDIP-10', 'minimal_nilai_utbk' => 685, 'minimal_nilai_snbp' => 850, 'kota' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
    ['nama' => 'Universitas Padjadjaran', 'prodi_id' => 4, 'kode_prodi' => 'UNPAD-04', 'minimal_nilai_utbk' => 695, 'minimal_nilai_snbp' => 860, 'kota' => 'Sumedang', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Padjadjaran', 'prodi_id' => 11, 'kode_prodi' => 'UNPAD-11', 'minimal_nilai_utbk' => 675, 'minimal_nilai_snbp' => 845, 'kota' => 'Sumedang', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Institut Pertanian Bogor', 'prodi_id' => 12, 'kode_prodi' => 'IPB-12', 'minimal_nilai_utbk' => 710, 'minimal_nilai_snbp' => 880, 'kota' => 'Bogor', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Institut Pertanian Bogor', 'prodi_id' => 13, 'kode_prodi' => 'IPB-13', 'minimal_nilai_utbk' => 670, 'minimal_nilai_snbp' => 820, 'kota' => 'Bogor', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Brawijaya', 'prodi_id' => 14, 'kode_prodi' => 'UB-14', 'minimal_nilai_utbk' => 685, 'minimal_nilai_snbp' => 850, 'kota' => 'Malang', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Brawijaya', 'prodi_id' => 15, 'kode_prodi' => 'UB-15', 'minimal_nilai_utbk' => 695, 'minimal_nilai_snbp' => 860, 'kota' => 'Malang', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Hasanuddin', 'prodi_id' => 16, 'kode_prodi' => 'UNHAS-16', 'minimal_nilai_utbk' => 670, 'minimal_nilai_snbp' => 830, 'kota' => 'Makassar', 'provinsi' => 'Sulawesi Selatan'],
    ['nama' => 'Universitas Hasanuddin', 'prodi_id' => 6, 'kode_prodi' => 'UNHAS-06', 'minimal_nilai_utbk' => 665, 'minimal_nilai_snbp' => 810, 'kota' => 'Makassar', 'provinsi' => 'Sulawesi Selatan'],
    ['nama' => 'Universitas Andalas', 'prodi_id' => 17, 'kode_prodi' => 'UNAND-17', 'minimal_nilai_utbk' => 665, 'minimal_nilai_snbp' => 820, 'kota' => 'Padang', 'provinsi' => 'Sumatera Barat'],
    ['nama' => 'Universitas Andalas', 'prodi_id' => 18, 'kode_prodi' => 'UNAND-18', 'minimal_nilai_utbk' => 650, 'minimal_nilai_snbp' => 800, 'kota' => 'Padang', 'provinsi' => 'Sumatera Barat'],
    ['nama' => 'Universitas Sumatera Utara', 'prodi_id' => 6, 'kode_prodi' => 'USU-06', 'minimal_nilai_utbk' => 660, 'minimal_nilai_snbp' => 815, 'kota' => 'Medan', 'provinsi' => 'Sumatera Utara'],
    ['nama' => 'Universitas Sumatera Utara', 'prodi_id' => 2, 'kode_prodi' => 'USU-02', 'minimal_nilai_utbk' => 665, 'minimal_nilai_snbp' => 825, 'kota' => 'Medan', 'provinsi' => 'Sumatera Utara'],
    ['nama' => 'Universitas Negeri Yogyakarta', 'prodi_id' => 19, 'kode_prodi' => 'UNY-19', 'minimal_nilai_utbk' => 655, 'minimal_nilai_snbp' => 810, 'kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Negeri Yogyakarta', 'prodi_id' => 20, 'kode_prodi' => 'UNY-20', 'minimal_nilai_utbk' => 645, 'minimal_nilai_snbp' => 800, 'kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Negeri Malang', 'prodi_id' => 21, 'kode_prodi' => 'UM-21', 'minimal_nilai_utbk' => 650, 'minimal_nilai_snbp' => 805, 'kota' => 'Malang', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Negeri Malang', 'prodi_id' => 5, 'kode_prodi' => 'UM-05', 'minimal_nilai_utbk' => 660, 'minimal_nilai_snbp' => 810, 'kota' => 'Malang', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Sebelas Maret', 'prodi_id' => 22, 'kode_prodi' => 'UNS-22', 'minimal_nilai_utbk' => 660, 'minimal_nilai_snbp' => 815, 'kota' => 'Surakarta', 'provinsi' => 'Jawa Tengah'],
    ['nama' => 'Universitas Sebelas Maret', 'prodi_id' => 23, 'kode_prodi' => 'UNS-23', 'minimal_nilai_utbk' => 720, 'minimal_nilai_snbp' => 910, 'kota' => 'Surakarta', 'provinsi' => 'Jawa Tengah'],
    ['nama' => 'Universitas Pendidikan Indonesia', 'prodi_id' => 24, 'kode_prodi' => 'UPI-24', 'minimal_nilai_utbk' => 630, 'minimal_nilai_snbp' => 790, 'kota' => 'Bandung', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Pendidikan Indonesia', 'prodi_id' => 25, 'kode_prodi' => 'UPI-25', 'minimal_nilai_utbk' => 650, 'minimal_nilai_snbp' => 805, 'kota' => 'Bandung', 'provinsi' => 'Jawa Barat'],
    ['nama' => 'Universitas Negeri Semarang', 'prodi_id' => 26, 'kode_prodi' => 'UNNES-26', 'minimal_nilai_utbk' => 640, 'minimal_nilai_snbp' => 795, 'kota' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
    ['nama' => 'Universitas Negeri Semarang', 'prodi_id' => 10, 'kode_prodi' => 'UNNES-10', 'minimal_nilai_utbk' => 655, 'minimal_nilai_snbp' => 810, 'kota' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
    ['nama' => 'Universitas Jember', 'prodi_id' => 27, 'kode_prodi' => 'UNEJ-27', 'minimal_nilai_utbk' => 635, 'minimal_nilai_snbp' => 785, 'kota' => 'Jember', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Jember', 'prodi_id' => 28, 'kode_prodi' => 'UNEJ-28', 'minimal_nilai_utbk' => 625, 'minimal_nilai_snbp' => 770, 'kota' => 'Jember', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Lampung', 'prodi_id' => 29, 'kode_prodi' => 'UNILA-29', 'minimal_nilai_utbk' => 640, 'minimal_nilai_snbp' => 800, 'kota' => 'Bandar Lampung', 'provinsi' => 'Lampung'],
    ['nama' => 'Universitas Lampung', 'prodi_id' => 30, 'kode_prodi' => 'UNILA-30', 'minimal_nilai_utbk' => 620, 'minimal_nilai_snbp' => 770, 'kota' => 'Bandar Lampung', 'provinsi' => 'Lampung'],
    ['nama' => 'Universitas Sriwijaya', 'prodi_id' => 17, 'kode_prodi' => 'UNSRI-17', 'minimal_nilai_utbk' => 640, 'minimal_nilai_snbp' => 790, 'kota' => 'Indralaya', 'provinsi' => 'Sumatera Selatan'],
    ['nama' => 'Universitas Sriwijaya', 'prodi_id' => 31, 'kode_prodi' => 'UNSRI-31', 'minimal_nilai_utbk' => 630, 'minimal_nilai_snbp' => 780, 'kota' => 'Indralaya', 'provinsi' => 'Sumatera Selatan'],
    ['nama' => 'Universitas Udayana', 'prodi_id' => 11, 'kode_prodi' => 'UNUD-11', 'minimal_nilai_utbk' => 645, 'minimal_nilai_snbp' => 795, 'kota' => 'Badung', 'provinsi' => 'Bali'],
    ['nama' => 'Universitas Udayana', 'prodi_id' => 32, 'kode_prodi' => 'UNUD-32', 'minimal_nilai_utbk' => 635, 'minimal_nilai_snbp' => 785, 'kota' => 'Badung', 'provinsi' => 'Bali'],
    ['nama' => 'Universitas Riau', 'prodi_id' => 1, 'kode_prodi' => 'UNRI-01', 'minimal_nilai_utbk' => 640, 'minimal_nilai_snbp' => 795, 'kota' => 'Pekanbaru', 'provinsi' => 'Riau'],
    ['nama' => 'Universitas Riau', 'prodi_id' => 3, 'kode_prodi' => 'UNRI-03', 'minimal_nilai_utbk' => 620, 'minimal_nilai_snbp' => 775, 'kota' => 'Pekanbaru', 'provinsi' => 'Riau'],
    ['nama' => 'Universitas Bengkulu', 'prodi_id' => 2, 'kode_prodi' => 'UNIB-02', 'minimal_nilai_utbk' => 615, 'minimal_nilai_snbp' => 770, 'kota' => 'Bengkulu', 'provinsi' => 'Bengkulu'],
    ['nama' => 'Universitas Bengkulu', 'prodi_id' => 4, 'kode_prodi' => 'UNIB-04', 'minimal_nilai_utbk' => 610, 'minimal_nilai_snbp' => 765, 'kota' => 'Bengkulu', 'provinsi' => 'Bengkulu'],
    ['nama' => 'Universitas Jambi', 'prodi_id' => 5, 'kode_prodi' => 'UNJA-05', 'minimal_nilai_utbk' => 625, 'minimal_nilai_snbp' => 780, 'kota' => 'Jambi', 'provinsi' => 'Jambi'],
    ['nama' => 'Universitas Jambi', 'prodi_id' => 7, 'kode_prodi' => 'UNJA-07', 'minimal_nilai_utbk' => 600, 'minimal_nilai_snbp' => 755, 'kota' => 'Jambi', 'provinsi' => 'Jambi'],
    ['nama' => 'Universitas Palangka Raya', 'prodi_id' => 6, 'kode_prodi' => 'UPR-06', 'minimal_nilai_utbk' => 590, 'minimal_nilai_snbp' => 745, 'kota' => 'Palangka Raya', 'provinsi' => 'Kalimantan Tengah'],
    ['nama' => 'Universitas Palangka Raya', 'prodi_id' => 8, 'kode_prodi' => 'UPR-08', 'minimal_nilai_utbk' => 585, 'minimal_nilai_snbp' => 740, 'kota' => 'Palangka Raya', 'provinsi' => 'Kalimantan Tengah'],
    ['nama' => 'Universitas Tanjungpura', 'prodi_id' => 9, 'kode_prodi' => 'UNTAN-09', 'minimal_nilai_utbk' => 605, 'minimal_nilai_snbp' => 760, 'kota' => 'Pontianak', 'provinsi' => 'Kalimantan Barat'],
    ['nama' => 'Universitas Tanjungpura', 'prodi_id' => 10, 'kode_prodi' => 'UNTAN-10', 'minimal_nilai_utbk' => 595, 'minimal_nilai_snbp' => 750, 'kota' => 'Pontianak', 'provinsi' => 'Kalimantan Barat'],
    ['nama' => 'Universitas Lambung Mangkurat', 'prodi_id' => 11, 'kode_prodi' => 'ULM-11', 'minimal_nilai_utbk' => 610, 'minimal_nilai_snbp' => 765, 'kota' => 'Banjarmasin', 'provinsi' => 'Kalimantan Selatan'],
    ['nama' => 'Universitas Lambung Mangkurat', 'prodi_id' => 12, 'kode_prodi' => 'ULM-12', 'minimal_nilai_utbk' => 600, 'minimal_nilai_snbp' => 755, 'kota' => 'Banjarmasin', 'provinsi' => 'Kalimantan Selatan'],
    ['nama' => 'Universitas Mulawarman', 'prodi_id' => 13, 'kode_prodi' => 'UNMUL-13', 'minimal_nilai_utbk' => 615, 'minimal_nilai_snbp' => 770, 'kota' => 'Samarinda', 'provinsi' => 'Kalimantan Timur'],
    ['nama' => 'Universitas Mulawarman', 'prodi_id' => 14, 'kode_prodi' => 'UNMUL-14', 'minimal_nilai_utbk' => 605, 'minimal_nilai_snbp' => 760, 'kota' => 'Samarinda', 'provinsi' => 'Kalimantan Timur'],
    ['nama' => 'Universitas Tadulako', 'prodi_id' => 15, 'kode_prodi' => 'UNTAD-15', 'minimal_nilai_utbk' => 580, 'minimal_nilai_snbp' => 735, 'kota' => 'Palu', 'provinsi' => 'Sulawesi Tengah'],
    ['nama' => 'Universitas Tadulako', 'prodi_id' => 16, 'kode_prodi' => 'UNTAD-16', 'minimal_nilai_utbk' => 575, 'minimal_nilai_snbp' => 730, 'kota' => 'Palu', 'provinsi' => 'Sulawesi Tengah'],
    ['nama' => 'Universitas Halu Oleo', 'prodi_id' => 17, 'kode_prodi' => 'UHO-17', 'minimal_nilai_utbk' => 585, 'minimal_nilai_snbp' => 740, 'kota' => 'Kendari', 'provinsi' => 'Sulawesi Tenggara'],
    ['nama' => 'Universitas Halu Oleo', 'prodi_id' => 18, 'kode_prodi' => 'UHO-18', 'minimal_nilai_utbk' => 580, 'minimal_nilai_snbp' => 735, 'kota' => 'Kendari', 'provinsi' => 'Sulawesi Tenggara'],
    ['nama' => 'Universitas Sam Ratulangi', 'prodi_id' => 19, 'kode_prodi' => 'UNSRAT-19', 'minimal_nilai_utbk' => 590, 'minimal_nilai_snbp' => 745, 'kota' => 'Manado', 'provinsi' => 'Sulawesi Utara'],
    ['nama' => 'Universitas Sam Ratulangi', 'prodi_id' => 20, 'kode_prodi' => 'UNSRAT-20', 'minimal_nilai_utbk' => 585, 'minimal_nilai_snbp' => 740, 'kota' => 'Manado', 'provinsi' => 'Sulawesi Utara'],
    ['nama' => 'Universitas Gorontalo', 'prodi_id' => 21, 'kode_prodi' => 'UNG-21', 'minimal_nilai_utbk' => 570, 'minimal_nilai_snbp' => 725, 'kota' => 'Gorontalo', 'provinsi' => 'Gorontalo'],
    ['nama' => 'Universitas Gorontalo', 'prodi_id' => 22, 'kode_prodi' => 'UNG-22', 'minimal_nilai_utbk' => 565, 'minimal_nilai_snbp' => 720, 'kota' => 'Gorontalo', 'provinsi' => 'Gorontalo'],
    ['nama' => 'Universitas Pattimura', 'prodi_id' => 23, 'kode_prodi' => 'UNPATTI-23', 'minimal_nilai_utbk' => 575, 'minimal_nilai_snbp' => 730, 'kota' => 'Ambon', 'provinsi' => 'Maluku'],
    ['nama' => 'Universitas Pattimura', 'prodi_id' => 24, 'kode_prodi' => 'UNPATTI-24', 'minimal_nilai_utbk' => 570, 'minimal_nilai_snbp' => 725, 'kota' => 'Ambon', 'provinsi' => 'Maluku'],
    ['nama' => 'Universitas Cenderawasih', 'prodi_id' => 25, 'kode_prodi' => 'UNCEN-25', 'minimal_nilai_utbk' => 565, 'minimal_nilai_snbp' => 720, 'kota' => 'Jayapura', 'provinsi' => 'Papua'],
    ['nama' => 'Universitas Cenderawasih', 'prodi_id' => 26, 'kode_prodi' => 'UNCEN-26', 'minimal_nilai_utbk' => 560, 'minimal_nilai_snbp' => 715, 'kota' => 'Jayapura', 'provinsi' => 'Papua'],
    ['nama' => 'Universitas Negeri Jakarta', 'prodi_id' => 27, 'kode_prodi' => 'UNJ-27', 'minimal_nilai_utbk' => 675, 'minimal_nilai_snbp' => 830, 'kota' => 'Jakarta', 'provinsi' => 'DKI Jakarta'],
    ['nama' => 'Universitas Negeri Jakarta', 'prodi_id' => 28, 'kode_prodi' => 'UNJ-28', 'minimal_nilai_utbk' => 670, 'minimal_nilai_snbp' => 825, 'kota' => 'Jakarta', 'provinsi' => 'DKI Jakarta'],
    ['nama' => 'Universitas Syiah Kuala', 'prodi_id' => 29, 'kode_prodi' => 'UNSYIAH-29', 'minimal_nilai_utbk' => 630, 'minimal_nilai_snbp' => 785, 'kota' => 'Banda Aceh', 'provinsi' => 'Aceh'],
    ['nama' => 'Universitas Syiah Kuala', 'prodi_id' => 30, 'kode_prodi' => 'UNSYIAH-30', 'minimal_nilai_utbk' => 625, 'minimal_nilai_snbp' => 780, 'kota' => 'Banda Aceh', 'provinsi' => 'Aceh'],
    ['nama' => 'Universitas Medan Area', 'prodi_id' => 31, 'kode_prodi' => 'UMA-31', 'minimal_nilai_utbk' => 580, 'minimal_nilai_snbp' => 735, 'kota' => 'Medan', 'provinsi' => 'Sumatera Utara'],
    ['nama' => 'Universitas Medan Area', 'prodi_id' => 32, 'kode_prodi' => 'UMA-32', 'minimal_nilai_utbk' => 575, 'minimal_nilai_snbp' => 730, 'kota' => 'Medan', 'provinsi' => 'Sumatera Utara'],
    ['nama' => 'Universitas Bung Hatta', 'prodi_id' => 1, 'kode_prodi' => 'UBH-01', 'minimal_nilai_utbk' => 590, 'minimal_nilai_snbp' => 745, 'kota' => 'Padang', 'provinsi' => 'Sumatera Barat'],
    ['nama' => 'Universitas Bung Hatta', 'prodi_id' => 2, 'kode_prodi' => 'UBH-02', 'minimal_nilai_utbk' => 585, 'minimal_nilai_snbp' => 740, 'kota' => 'Padang', 'provinsi' => 'Sumatera Barat'],
    ['nama' => 'Universitas Bina Darma', 'prodi_id' => 3, 'kode_prodi' => 'BINADARMA-03', 'minimal_nilai_utbk' => 570, 'minimal_nilai_snbp' => 725, 'kota' => 'Palembang', 'provinsi' => 'Sumatera Selatan'],
    ['nama' => 'Universitas Bina Darma', 'prodi_id' => 4, 'kode_prodi' => 'BINADARMA-04', 'minimal_nilai_utbk' => 565, 'minimal_nilai_snbp' => 720, 'kota' => 'Palembang', 'provinsi' => 'Sumatera Selatan'],
    ['nama' => 'Universitas Teknologi Yogyakarta', 'prodi_id' => 5, 'kode_prodi' => 'UTY-05', 'minimal_nilai_utbk' => 600, 'minimal_nilai_snbp' => 755, 'kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Teknologi Yogyakarta', 'prodi_id' => 6, 'kode_prodi' => 'UTY-06', 'minimal_nilai_utbk' => 595, 'minimal_nilai_snbp' => 750, 'kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Muhammadiyah Yogyakarta', 'prodi_id' => 7, 'kode_prodi' => 'UMY-07', 'minimal_nilai_utbk' => 580, 'minimal_nilai_snbp' => 735, 'kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Muhammadiyah Yogyakarta', 'prodi_id' => 8, 'kode_prodi' => 'UMY-08', 'minimal_nilai_utbk' => 575, 'minimal_nilai_snbp' => 730, 'kota' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],
    ['nama' => 'Universitas Mataram', 'prodi_id' => 6, 'kode_prodi' => 'UNRAM-33', 'minimal_nilai_utbk' => 620, 'minimal_nilai_snbp' => 775, 'kota' => 'Mataram', 'provinsi' => 'Nusa Tenggara Barat'],
    ['nama' => 'Universitas Mataram', 'prodi_id' => 10, 'kode_prodi' => 'UNRAM-34', 'minimal_nilai_utbk' => 610, 'minimal_nilai_snbp' => 765, 'kota' => 'Mataram', 'provinsi' => 'Nusa Tenggara Barat'],
    ['nama' => 'Universitas Nusa Cendana', 'prodi_id' => 33, 'kode_prodi' => 'UNDANA-35', 'minimal_nilai_utbk' => 585, 'minimal_nilai_snbp' => 740, 'kota' => 'Kupang', 'provinsi' => 'Nusa Tenggara Timur'],
    ['nama' => 'Universitas Nusa Cendana', 'prodi_id' => 34, 'kode_prodi' => 'UNDANA-36', 'minimal_nilai_utbk' => 580, 'minimal_nilai_snbp' => 735, 'kota' => 'Kupang', 'provinsi' => 'Nusa Tenggara Timur'],
    ['nama' => 'Universitas Malikussaleh', 'prodi_id' => 3, 'kode_prodi' => 'UNIMAL-37', 'minimal_nilai_utbk' => 600, 'minimal_nilai_snbp' => 755, 'kota' => 'Lhokseumawe', 'provinsi' => 'Aceh'],
    ['nama' => 'Universitas Malikussaleh', 'prodi_id' => 9, 'kode_prodi' => 'UNIMAL-38', 'minimal_nilai_utbk' => 595, 'minimal_nilai_snbp' => 750, 'kota' => 'Lhokseumawe', 'provinsi' => 'Aceh'],
    ['nama' => 'Universitas Sultan Ageng Tirtayasa', 'prodi_id' => 5, 'kode_prodi' => 'UNTIRTA-39', 'minimal_nilai_utbk' => 625, 'minimal_nilai_snbp' => 780, 'kota' => 'Serang', 'provinsi' => 'Banten'],
    ['nama' => 'Universitas Sultan Ageng Tirtayasa', 'prodi_id' => 35, 'kode_prodi' => 'UNTIRTA-40', 'minimal_nilai_utbk' => 615, 'minimal_nilai_snbp' => 770, 'kota' => 'Serang', 'provinsi' => 'Banten'],
    ['nama' => 'Universitas Trunojoyo Madura', 'prodi_id' => 36, 'kode_prodi' => 'UTM-41', 'minimal_nilai_utbk' => 605, 'minimal_nilai_snbp' => 760, 'kota' => 'Bangkalan', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Trunojoyo Madura', 'prodi_id' => 27, 'kode_prodi' => 'UTM-42', 'minimal_nilai_utbk' => 600, 'minimal_nilai_snbp' => 755, 'kota' => 'Bangkalan', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Negeri Surabaya', 'prodi_id' => 21, 'kode_prodi' => 'UNESA-43', 'minimal_nilai_utbk' => 650, 'minimal_nilai_snbp' => 805, 'kota' => 'Surabaya', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Negeri Surabaya', 'prodi_id' => 19, 'kode_prodi' => 'UNESA-44', 'minimal_nilai_utbk' => 645, 'minimal_nilai_snbp' => 800, 'kota' => 'Surabaya', 'provinsi' => 'Jawa Timur'],
    ['nama' => 'Universitas Borneo Tarakan', 'prodi_id' => 37, 'kode_prodi' => 'UBT-45', 'minimal_nilai_utbk' => 590, 'minimal_nilai_snbp' => 745, 'kota' => 'Tarakan', 'provinsi' => 'Kalimantan Utara'],
    ['nama' => 'Universitas Borneo Tarakan', 'prodi_id' => 38, 'kode_prodi' => 'UBT-46', 'minimal_nilai_utbk' => 585, 'minimal_nilai_snbp' => 740, 'kota' => 'Tarakan', 'provinsi' => 'Kalimantan Utara'],
];


        foreach ($universitas as $dataUniversitas) {
            Universitas::create($dataUniversitas);
        }
    }
}
